{% set name = "pascal-voc-writer" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AndrewCarterUK/pascal-voc-writer/archive/v{{ version }}.tar.gz
  sha256: a03fbaefd98b090b74d3911c84c51f71cc17290abe7315e360b3036dbcf22ceb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - jinja2

test:
  imports:
    - pascal_voc_writer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AndrewCarterUK/pascal-voc-writer
  summary: 'Create image annotation XML files in the PASCAL VOC format'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - OliverEdy
